# Travis CI build file for Swift-Kuery-SQLite.
# Swift-Kuery-SQLite runs on OS X and Linux (Ubuntu).
# See the following URLs for further details on Travis CI
# https://docs.travis-ci.com/user/customizing-the-build/
# https://docs.travis-ci.com/user/docker/
# https://docs.travis-ci.com/user/multi-os/

# whitelist (branches that should be built)
branches:
  only:
    - master
    - /^issue.*$/

notifications:
  slack:
    secure: "DAc9sIaemc8eWlQFR9A0MyItEgfw2RGcZ/0aqtCbUv9MXDsJez6gKxFhaXuHHZkt8qG2GGdDZpGaaBusu+2/b/f1LbGOHa4Zmt7Sv99Vs4BZgrKorsKtXS2/7IQMqfZ/cHbCpOjE/yRxBhCjsoNHScFB+na9vUAi6Zr2aMJk1mcDHUym3TFR4w3Hm++p8JnfG5ZuuQO34Sc9NlznPqAORqffI6anZMuZ5SBghh1OzR14gqN87S9ljwOVb3fH1a1T8x7sn8nnG3bB+ju6IyF+ekfT/+nV/tl3QwM6XP9OfmLIfA/E0PT6KqUfUaaOiakefjLbSKihmwJWw3u2hLlgHp5JKj1iu3dnWi3kdId+nPgx0OaCCgIqZz4lgZ4NJ4ro8WxVVhCYkV+v8e3nMuGB6xVQlGAJBaG0PZijCNqq1WFgjL0i4XuK9j07067of9HKIPY9Hc+y0qb/U+ZK8vH210hlfxWtpKNIpP14KdDW+v9LLtQU/FEywbyhccuEsiyWGQqsTPfWnia9i4EEzzZmqgxQKQLOYlseMHw9iQlM+aUFobOvPdQ3JBosO/EhZrKGP3WP8kBiG8/6tD8Cyqk9MShzkDqgpmGN4zpUJ+hBb0z+UC4DhMCeo4JIvhlk1moTErA7gPBY1D54W7q8xZx7wQI9REGxgFz7TgUCaTfvzgc="

# the matrix of builds should cover each combination of Swift version
# and platform that is supported. The version of Swift used is specified
# by .swift-version, unless SWIFT_SNAPSHOT is specified.
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      env: SWIFT_SNAPSHOT=4.0.3
    - os: linux
      dist: trusty
      sudo: required
    - os: linux
      dist: trusty
      sudo: required
      env: SWIFT_SNAPSHOT=swift-4.2-DEVELOPMENT-SNAPSHOT-2018-06-19-a
    - os: osx
      osx_image: xcode9.2
      sudo: required
      env: SWIFT_SNAPSHOT=4.0.3
    - os: osx
      osx_image: xcode9.4
      sudo: required
      env: JAZZY_ELIGIBLE=true
    - os: osx
      osx_image: xcode9.4
      sudo: required
      env: SWIFT_SNAPSHOT=swift-4.2-DEVELOPMENT-SNAPSHOT-2018-06-04-a

before_install:
  - git clone https://github.com/IBM-Swift/Package-Builder.git

script:
  - ./Package-Builder/build-package.sh -projectDir $TRAVIS_BUILD_DIR
